version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "5173:5173"
            - "8080:8080"
        environment:
            PUBLIC_API_URL: http://localhost:8080
            NODE_ENV: development
            API_PORT: 8080
            CLIENT_ORIGIN_URL: http://localhost:5173
            DB_HOST: db
            DB_PORT: 5433
            DB_NAME: phiture
            DB_USER: elgatoloco
            DB_PASS: test123
        command: >
            sh -c "yarn workspace server migration:generate latest &&
                   yarn workspace server migration:run &&
                   yarn dev"
        volumes:
            - .:/app
            - /app/node_modules
    db:
        image: postgres:15.3
        expose:
            - "5433"
        ports:
            - "5433:5433"
        command: -p 5433
        environment:
            POSTGRES_DB: phiture
            POSTGRES_USER: elgatoloco
            POSTGRES_PASSWORD: test123
        volumes:
            - ./.postgres:/var/lib/postgresql/data
volumes:
  .postgres:
